<div id="modal-form" class="modal" tabindex="-1">
	<div class="modal-dialog">	
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger"><i class="icon-pencil"></i> Modifier la news à la une</h4>
			</div>

			<div class="modal-body overflow-visible">
				<form id="modifier">
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label bolder blue" for="titre">Titre de la news</label>	
							<div class="controls">
								<input type="text" id="titre" name="titre" value="<?=$this->alaune['titre']?>"/>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="control-label bolder blue" for="lien">Lien (optionnel)</label>	
							<div class="controls">
								<input type="text" id="lien" name="lien" value="<?=$this->alaune['lien']?>"/>
							</div>
						</div>
					</div>
					<div class="control-group col-md-12">
						<label class="control-label bolder blue	" for="description">Message</label>	
						<textarea name="contenu" class="autosize-transition form-control"><?=$this->alaune['contenu']?></textarea>
					</div>
				</form>
			</div>
			<div class="clearfix"></div>
			<div class="modal-footer">
				<button class="btn btn-sm btn-danger" data-dismiss="modal">
					<i class="icon-remove"></i>
					Annuler
				</button>

				<button class="btn btn-sm btn-primary" onclick="return home_modifier(1);">
					<i class="icon-ok"></i>
					Modifier
				</button>
			</div>
		</div>
	</div>
</div>