<!-- Begin Login Page -->
<div class="full-content-center animated fadeInDownBig">
	<i class="fa fa-rocket fa-5x"></i>
	<div class="login-wrap">
		<div class="box-info">
		<h2 class="text-center"><strong>Bil</strong>board</h2>
		
			<form role="form" action="/connexion" method="POST">
				<div class="form-group login-input">
				<i class="fa fa-sign-in overlay"></i>
				<input type="text" class="form-control text-input" name="mail" placeholder="Email">
				</div>
				<div class="form-group login-input">
				<i class="fa fa-key overlay"></i>
				<input type="password" class="form-control text-input" name="pass" placeholder="Password">
				</div>
				<div class="checkbox">
				<label>
					<input type="checkbox" name="remember"> Remember me
				</label>
				</div>
				
				<div class="row">
					<div class="col-sm-12">
					<button type="submit" class="btn btn-success btn-block"><i class="fa fa-unlock"></i> Login</button>
					</div>
				</div>
			</form>
		</div>
		<p class="text-center">
			<a href="/connexion/pass"><i class="fa fa-lock"></i> Forgot password?</a>
			&nbsp;&nbsp;&nbsp;
			<a href="/connexion/inscription"><i class="fa fa-flash"></i> Register</a>
		</p>
	</div>
</div>
<!-- End Login Page -->
<? if(isset($this->inactiv)) echo $this->inactiv; ?>