<!-- Begin Register Page -->
<div class="full-content-center animated fadeInDownBig">
	<i class="fa fa-rocket fa-5x"></i>
	<div class="login-wrap">
		<div class="box-info">
		<h2 class="text-center"><strong>Become</strong> a startuper</h2>
		
			<form role="form" method="POST" action="/connexion/inscription">
				<div class="form-group login-input">
					<i class="fa fa-user overlay"></i>
					<input type="text" class="form-control text-input" name="firstname" placeholder="Your firstname">
				</div>
				<div class="form-group login-input">
					<i class="fa fa-user overlay"></i>
					<input type="text" class="form-control text-input" name="lastname" placeholder="Your lastname">
				</div>
				<div class="form-group login-input">
					<i class="fa fa-envelope overlay"></i>
					<input type="email" class="form-control text-input" name="mail" placeholder="Your email">
				</div>
				<div class="form-group login-input">
					<i class="fa fa-key overlay"></i>
					<input type="password" class="form-control text-input" name="pass" placeholder="Password">
				</div>
				<button type="submit" class="btn btn-success btn-block"><i class="fa fa-rocket"></i> Register</button>
			</form>
		</div>
		<p class="text-center"><a href="/"><i class="fa fa-sign-in"></i> Back to login</a></p>
	</div>
</div>
<!-- End Register Page -->
