<!-- Page header -->
<div class="page-heading animated fadeInDownBig">
	<h1>User profile</h1>
</div>
<!-- End page header -->

<div class="row">
	<div class="col-sm-4">
		<div class="box-info">
			<!-- User profile avatar, name and location -->
			<div class="user-profile-sidebar">
				<h2><strong><?=$this->session->user['firstname']?> <?=$this->session->user['lastname']?>'s</strong> Profile</h2>
				<div class="row">
					<div class="col-md-4">
						<img src="/img/avatar/masarie.jpg" class="img-circle" alt="Avatar">
					</div>
					<div class="col-md-8">
						<!-- User identity -->
						<div class="user-identity">
							<h4><strong><?=$this->session->user['firstname']?> <?=$this->session->user['lastname']?></strong></h4>
							<p><i class="fa fa-map-marker"></i> Lyon, FR</p>
						</div><!-- End div .user-identity -->
					</div>
				</div>
			</div><!-- End div .user-profile-sidebar -->
			<!-- Account status -->
			<div class="account-status-data">
				<div class="row">
					<div class="col-md-4">
						<h5><strong>1,254</strong> Posts</h5>
					</div>
					<div class="col-md-4">
						<h5><strong>12</strong> Following</h5>
					</div>
					<div class="col-md-4">
						<h5><strong>100</strong> Followers</h5>
					</div>
				</div>
			</div><!-- End div .account-status-data -->
			<!-- User button -->
			<div class="user-button">
				<div class="row">
					<div class="col-md-6">
						<button type="button" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i> Send Message</button>
					</div>
					<div class="col-md-6">
						<button type="button" class="btn btn-default btn-sm btn-block"><i class="fa fa-user"></i> Add as friend</button>
					</div>
				</div>
			</div><!-- End div .user-button -->
			
			<h5>CONNECTION</h5>
			<!-- Social icon -->
			<div id="social">
				<a href="#fakelink" data-toggle="tooltip" title="Facebook">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle facebook fa-stack-2x"></i>
					  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Twitter">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle twitter fa-stack-2x"></i>
					  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Google Plus">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle gplus fa-stack-2x"></i>
					  <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Tumblr">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle tumblr fa-stack-2x"></i>
					  <i class="fa fa-tumblr fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Linkedin">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle linkedin fa-stack-2x"></i>
					  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
					</span>
				</a>
			</div><!-- End div #social -->
		</div><!-- End div .box-info -->
	</div><!-- End div .col-sm-4 -->
	
	<div class="col-sm-8">
		<div class="box-info full">
			<!-- Nav tab -->
			<ul class="nav nav-tabs nav-justified">
			  <li class="active"><a href="#about" data-toggle="tab"><i class="fa fa-cogs"></i> Settings</a></li>
			  <li><a href="#edit-profile" data-toggle="tab"><i class="fa fa-user"></i> Edit</a></li>
			</ul>
			<!-- End nav tab -->

			<!-- Tab panes -->
			<div class="tab-content">
				<!-- Tab about -->
				<div class="tab-pane active animated fadeInRight" id="about">
					<div class="user-profile-content">
						<h5><strong>Social Connect</strong></h5>
						<hr />
						<div class="row">
							<div class="col-sm-6">
								<div class="box-info full">
									<div class="table-responsive">
										<table data-sortable="" class="table" data-sortable-initialized="true">
											<thead>
												<tr>
													<th>Profil</th>
													<th>Disconnect</th>
												</tr>
											</thead>
											<tbody>
											<? foreach($this->links as $link): ?>
												<tr>
													<td><i class="fa fa-<?=strtolower(Model_Link::getTypeLabel($link['type']))?>"></i> <?=$link['title']?></td>
													<td><a class="btn btn-danger btn-xs" href="/link/delete?id=<?=$link['id']?>"><i class="fa fa-times"></i> Disconnect</a></td>
												</tr>
											<? endforeach; ?>
											</tbody>
										</table>
									</div><!-- End div .table-responsive -->
								</div>		<!-- Horizontal form -->
							</div>
							<div class="col-sm-6">
								<a class="btn btn-twitter btn-block" href="/link/twitter"><i class="fa fa-twitter"></i> Connect</a>
							</div>
						</div><!-- End div .row -->
					</div><!-- End div .user-profile-content -->
				</div><!-- End div .tab-pane -->
				<!-- End Tab about -->
				
				
				<!-- Tab edit profile -->
				<div class="tab-pane animated fadeInRight" id="edit-profile">
					<div class="user-profile-content">
						<form role="form" method="POST" action="/profil">
							<div class="form-group">
								<label for="firstname">Firstname</label>
								<input type="text" class="form-control" id="firstname" name="firstname" value="<?=$this->session->user['firstname']?>">
							</div>
							<div class="form-group">
								<label for="lastname">Lastname</label>
								<input type="text" class="form-control" id="lastname" name="lastname" value="<?=$this->session->user['lastname']?>">
							</div>
							<div class="form-group">
								<label for="mail">Email</label>
								<input type="email" class="form-control" id="mail" name="mail" value="<?=$this->session->user['mail']?>">
							</div>
							<div class="form-group">
								<label for="pass">Password</label>
								<input type="password" class="form-control" id="pass" name="pass" placeholder="New password">
							</div>
							<button type="submit" class="btn btn-primary">Save</button>
						</form>
					</div><!-- End div .user-profile-content -->
				</div><!-- End div .tab-pane -->
			  	<!-- End Tab Edit profile -->
				<!-- End Tab user links -->
			</div><!-- End div .tab-content -->
		</div><!-- End div .box-info -->
	</div><!-- End div .col-sm-8 -->
</div><!-- End div .row -->
