<!-- Page header -->
<div class="page-heading animated fadeInDownBig">
	<h1>User profile</h1>
</div>
<!-- End page header -->

<div class="row">
	<div class="col-sm-4">
		<div class="box-info">
			<!-- User profile avatar, name and location -->
			<div class="user-profile-sidebar">
				<h2><strong><?=$this->session->user['firstname']?> <?=$this->session->user['lastname']?>'s</strong> Profile</h2>
				<div class="row">
					<div class="col-md-4">
						<img src="assets/img/avatar/masarie.jpg" class="img-circle" alt="Avatar">
					</div>
					<div class="col-md-8">
						<!-- User identity -->
						<div class="user-identity">
							<h4><strong><?=$this->session->user['firstname']?> <?=$this->session->user['lastname']?></strong></h4>
							<p><i class="fa fa-map-marker"></i> Yogyakarta, ID</p>
						</div><!-- End div .user-identity -->
					</div>
				</div>
			</div><!-- End div .user-profile-sidebar -->
			<!-- Account status -->
			<div class="account-status-data">
				<div class="row">
					<div class="col-md-4">
						<h5><strong>1,254</strong> Posts</h5>
					</div>
					<div class="col-md-4">
						<h5><strong>12</strong> Following</h5>
					</div>
					<div class="col-md-4">
						<h5><strong>100</strong> Followers</h5>
					</div>
				</div>
			</div><!-- End div .account-status-data -->
			<!-- User button -->
			<div class="user-button">
				<div class="row">
					<div class="col-md-6">
						<button type="button" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i> Send Message</button>
					</div>
					<div class="col-md-6">
						<button type="button" class="btn btn-default btn-sm btn-block"><i class="fa fa-user"></i> Add as friend</button>
					</div>
				</div>
			</div><!-- End div .user-button -->
			
			<h5>CONNECTION</h5>
			<!-- Social icon -->
			<div id="social">
				<a href="#fakelink" data-toggle="tooltip" title="Facebook">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle facebook fa-stack-2x"></i>
					  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Twitter">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle twitter fa-stack-2x"></i>
					  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Google Plus">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle gplus fa-stack-2x"></i>
					  <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Tumblr">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle tumblr fa-stack-2x"></i>
					  <i class="fa fa-tumblr fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				<a href="#fakelink" data-toggle="tooltip" title="Linkedin">
					<span class="fa-stack fa-lg">
					  <i class="fa fa-circle linkedin fa-stack-2x"></i>
					  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
					</span>
				</a>
			</div><!-- End div #social -->
		</div><!-- End div .box-info -->
	</div><!-- End div .col-sm-4 -->
	
	<div class="col-sm-8">
		<div class="box-info full">
			<!-- Nav tab -->
			<ul class="nav nav-tabs nav-justified">
			  <li class="active"><a href="#about" data-toggle="tab"><i class="fa fa-user"></i> About</a></li>
			  <li><a href="#edit-profile" data-toggle="tab"><i class="fa fa-pencil"></i> Edit</a></li>
			  <li><a href="#user-links" data-toggle="tab"><i class="fa fa-laptop"></i> Social Links</a></li>
			  <li><a href="#mymessage" data-toggle="tab"><i class="fa fa-envelope"></i> Message</a></li>
			</ul>
			<!-- End nav tab -->

			<!-- Tab panes -->
			<div class="tab-content">
				<!-- Tab about -->
				<div class="tab-pane active animated fadeInRight" id="about">
					<div class="user-profile-content">
						<h5><strong>ABOUT</strong> ME</h5>
						<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
						</p>
						<hr />
						<div class="row">
							<div class="col-sm-6">
								<h5><strong>CONTACT</strong> ME</h5>
									<address>
										<strong>Phone</strong><br>
										<abbr title="Phone">+62 857 123 4567</abbr>
									</address>
									<address>
										<strong>Email</strong><br>
										<a href="mailto:#">first.last@example.com</a>
									</address>
									<address>
										<strong>Website</strong><br>
										<a href="http://ariecupu.com">http://ariecupu.com</a>
									</address>
							</div>
							<div class="col-sm-6">
								<h5><strong>MY</strong> SKILLS</h5>
								<p>UI Design</p>
								<p>Clean and Modern Web Design</p>
								<p>PHP and MySQL Programming</p>
								<p>Vector Design</p>
							</div>
						</div><!-- End div .row -->
					</div><!-- End div .user-profile-content -->
				</div><!-- End div .tab-pane -->
				<!-- End Tab about -->
				
				
				<!-- Tab edit profile -->
				<div class="tab-pane animated fadeInRight" id="edit-profile">
					<div class="user-profile-content">
						<form role="form">
							<div class="form-group">
								<label for="FullName">Full Name</label>
								<input type="text" class="form-control" id="FullName" value="Mas Bro Rusmanto">
							</div>
							<div class="form-group">
								<label for="Email">Email</label>
								<input type="email" class="form-control" id="Email" value="first.last@example.com">
							</div>
							<div class="form-group">
								<label for="Username">Username</label>
								<input type="text" class="form-control" id="Username" value="masbro">
							</div>
							<div class="form-group">
								<label for="Password">Password</label>
								<input type="password" class="form-control" id="Password" placeholder="6 - 15 Characters">
							</div>
							<div class="form-group">
								<label for="RePassword">Re-Password</label>
								<input type="password" class="form-control" id="RePassword" placeholder="6 - 15 Characters">
							</div>
							<div class="form-group">
								<label for="AboutMe">About Me</label>
								<textarea class="form-control" id="AboutMe" style="height: 125px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</textarea>
							</div>
							<button type="submit" class="btn btn-primary">Save</button>
						</form>
					</div><!-- End div .user-profile-content -->
				</div><!-- End div .tab-pane -->
			  	<!-- End Tab Edit profile -->
				
				
				<!-- Tab user links -->
				<div class="tab-pane animated fadeInRight" id="user-links">
					<div class="scroll-user-widget">
						<a href="/link/twitter" title="Ajouter un compte Twitter">
							<button type="button" class="btn btn-info">Ajouter un compte Twitter</button>
						</a>
						<ul class="media-list">
						<?php if(is_array($this->links)): ?>
							<?php foreach($this->links as $link): ?>
							
								<li class="media">
									<h4><?php echo Model_Link::getTypeLabel($link['type']); ?>
									<?php echo $link['title']; ?></h4>
									<form action="/link/delete" method="post">
										<input type="hidden" name="id" value="<?php echo $link['id']; ?>"/>
										<button type="submit" class="btn btn-link">Supprimer</button>
									</form>
								</li>
							<?php endforeach; ?>
						<?php endif; ?>
						</ul>
					</div><!-- End div .scroll-user-widget -->
				</div><!-- End div .tab-pane -->
				<!-- End Tab user links -->
				
				<!-- Tab user messages -->
				<div class="tab-pane animated fadeInRight" id="mymessage">
					<div class="scroll-user-widget">
						<ul class="media-list">
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/2.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">John Doe</a> <small>Just now</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/1.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Annisa</a> <small>Yesterday at 04:00 AM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/5.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Rusmanovski</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/4.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Ari Rusmanto</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/3.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Jenny Doe</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/2.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">John Doe</a> <small>Just now</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/1.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Annisa</a> <small>Yesterday at 04:00 AM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/5.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Rusmanovski</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/4.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Ari Rusmanto</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						  <li class="media">
							<a class="pull-left" href="#fakelink">
							  <img class="media-object" src="assets/img/avatar/3.jpg" alt="Avatar">
							</a>
							<div class="media-body">
							  <h4 class="media-heading"><a href="#fakelink">Jenny Doe</a> <small>January 17, 2014 05:35 PM</small></h4>
							  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
							</div>
						  </li>
						</ul>
					</div><!-- End div .scroll-user-widget -->
				</div><!-- End div .tab-pane -->
				<!-- End Tab user messages -->
			</div><!-- End div .tab-content -->
		</div><!-- End div .box-info -->
	</div><!-- End div .col-sm-8 -->
</div><!-- End div .row -->
