<?
	$this->headScript()
		->appendFile('/js/app/dailybil.js','text/javascript');		
?>
<div class="page-heading animated fadeInDownBig">
	<h1>Dailybil <small>CM as a service</small></h1>
</div>
<div class="row">
	<div class="col-sm-6">
		<!-- Basic form -->
		<div class="box-info">
			<h2><strong>Enregistrer</strong> un nouveau filtre</h2>
			<!-- Additional button -->
			<div class="additional-btn">
				<a class="additional-icon" href="#fakelink"><i class="fa fa-question-circle"></i></a>
			</div>
			<!-- Basic form body -->
			<div id="basic-form" class="collapse in">
				<form id="dailybil" method="POST" action="/dailybil">
				  <div class="form-group">
					<label for="categories">#Hashtags</label>
					<select class="form-control" name="categories[]" id="categories" multiple>
					<? foreach($this->categories as $categorie) : ?>
						<option value="<?=$categorie?>"><?=$categorie?></option>
					<? endforeach; ?>
					</select>
				  </div>
				  <div class="form-group">
					<label for="exampleInputPassword1">Compte Twitter</label>
					<select class="form-control" name="token">
					<? foreach($this->links as $link) : ?>
						<option value="<?=$link['connectionObject']?>"><?=$link['title']?></option>
					<? endforeach; ?>
					</select>
					<p class="help-block"><a href="/profil">Linker un nouveau compte</a></p>
				  </div>
				  <button class="btn btn-default" onclick="return preview();">Preview</button>
				  <button type="submit" class="btn btn-default">Save</button>
				</form>
			</div><!-- End div #basic-form -->
		</div><!-- End div .box-info -->
	</div><!-- End div .col-sm-6 -->
	<div class="col-sm-6">
		<div class="box-info">
			<h2><strong>Preview</strong></h2>
			<p id="preview"></p>
		</div><!-- End div .box-info -->
	</div>
</div><!-- End div .row -->
<div class="row">
	<div class="col-sm-6">
		<div class="box-info full">
			<div class="table-responsive">
				<table data-sortable="" class="table" data-sortable-initialized="true">
					<thead>
						<tr>
							<th>Compte</th>
							<th>Hashtags</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
					<? foreach($this->searches as $key => $searchesByUser): ?>
						<? foreach($searchesByUser as $search): ?>
						<tr>
							<td><?=$key?></td>
							<td><?=implode(',',$search)?></td>
							<td><a href="/dailybil/delete?token="><i class="fa fa-times"></i></a></td>
						</tr>
						<? endforeach; ?>
					<? endforeach; ?>
					</tbody>
				</table>
			</div><!-- End div .table-responsive -->
		</div>		<!-- Horizontal form -->
	</div><!-- End div .col-sm-6 -->
</div>
<div class="clearfix"></div>
