<?
	$this->headScript()
		->appendFile('/js/app/dailybil.js','text/javascript');		
?>
<div class="page-heading animated fadeInDownBig">
	<h1>Dailybil <small>CM as a service</small></h1>
</div>
<div class="row">
	<div class="col-sm-6">
		<!-- Basic form -->
		<div class="box-info">
			<h2><strong>Enregistrer</strong> un nouveau filtre</h2>
			<!-- Additional button -->
			<div class="additional-btn">
				<a class="additional-icon" href="#fakelink"><i class="fa fa-question-circle"></i></a>
			</div>
			<!-- Basic form body -->
			<div id="basic-form" class="collapse in">
				<form id="dailybil" method="POST" action="/dailybil">
				  <div class="form-group">
					<label for="categories">#Hashtags</label>
					<select class="form-control" name="categories[]" id="categories" multiple>
					<? foreach($this->categories as $categorie) : ?>
						<option value="<?=$categorie?>"><?=$categorie?></option>
					<? endforeach; ?>
					</select>
				  </div>
				  <div class="form-group">
					<label for="exampleInputPassword1">Compte Twitter</label>
					<select class="form-control" name="title">
					<? foreach($this->links as $link) : ?>
						<option value="<?=$link['title']?>"><?=$link['title']?></option>
					<? endforeach; ?>
					</select>
					<p class="help-block"><a href="/profil">Linker un nouveau compte</a></p>
				  </div>
				  <button class="btn btn-default" onclick="return preview();">Preview</button>
				  <button type="submit" class="btn btn-default">Save</button>
				</form>
			</div><!-- End div #basic-form -->
		</div><!-- End div .box-info -->
		<div class="box-info full">
			<div class="table-responsive">
				<table data-sortable="" class="table" data-sortable-initialized="true">
					<thead>
						<tr>
							<th>Compte</th>
							<th>Hashtags</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
					<? foreach($this->searches as $key => $searchesByUser): ?>
						<? foreach($searchesByUser as $search): ?>
						<tr>
							<td><?=$key?></td>
							<td><?=implode(',',$search)?></td>
							<td><a href="/dailybil/delete?title=<?=$key?>&categories=<?=urlencode(implode(',',$search))?>"><i class="fa fa-times"></i></a></td>
						</tr>
						<? endforeach; ?>
					<? endforeach; ?>
					</tbody>
				</table>
			</div><!-- End div .table-responsive -->
		</div>		<!-- Horizontal form -->
	</div><!-- End div .col-sm-6 -->
	<div class="col-sm-6">
		<div class="box-info">
			<a href="https://github.com/HackBil/DailyBIL-extension/archive/master.zip" target="_blank" class="btn btn-success btn-lg btn-block"><i class="fa fa-tags"></i> Télécharger le plugin Chrome</a>
		</div>
		<div class="box-info">
			<h2><strong>Preview</strong></h2>
			<div id="preview">
				<div class="the-notes info">
					<h4>Qu'est-ce que le DailyBil ?</h4>
					<p>Le Dailybil est un outil de veille collaborative :</p>
					<ol>
						<li>
							<strong>Installez le plugin Chrome</strong> disponible ci-dessus (enregistrer le dossier dézippé dans un dossier fixe de votre ordinateur, puis rdv dans Chrome, Outils, Extension, mode développeur activé puis charger l'extension non-empaquetée)
						</li>
						<li>
							<strong>Enregistrer les articles qui vous intéressent</strong> : lorsque vous êtes sur la page de l'article, cliquez sur l'icône de l'extension, puis renseignez les hashtags (sans le #), vous pouvez également recalibrer le titre s'il ne vous semble pas bon, et enfin préciser le compte que vous souhaitez mettre en avant avec cet article.
						</li>
						<li>
							<strong>Définissez les règles d'autopublication</strong> : car le Dailybil est également un outil de publication, sélectionnez le compe Twitter que vous souhaitez alimenter ainsi que les catégories que vous souhaitez filtrer (on parle ici d'intersection).
						</li>
						<li>
							<strong>Magie !</strong> Le robot alimentera désormais le compte Twitter désigné avec les contenus issus de la veille de l'ensemble des copains du réseau !
						</li>
					</ol>
				</div>			
			</div>
		</div><!-- End div .box-info -->
	</div>
</div><!-- End div .row -->