<!-- Begin Forgot Password Page -->
<div class="full-content-center animated fadeInDownBig">
	<i class="fa fa-rocket fa-5x"></i>
	<div class="login-wrap">
		<div class="box-info">
		<h2 class="text-center"><strong>Lo</strong>ser</h2>
		
			<form role="form" method="POST" action="/connexion/pass">
				<div class="form-group login-input">
				<i class="fa fa-user overlay"></i>
				<input type="email" class="form-control text-input" name="pass" placeholder="Your email">
				</div>
				
				<button type="button" class="btn btn-success btn-block"><i class="fa fa-lock"></i> Reset Password</button>
			</form>
		</div>
		<p class="text-center"><a href="/"><i class="fa fa-sign-in"></i> Back to login</a></p>
	</div>
</div>
<!-- End Forgot Password Page -->