<!DOCTYPE html>
<html>
	<head>
	<title>Welcome on Board !</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="description" content="">
	<meta name="keywords" content="admin, bootstrap,admin template, bootstrap admin, simple, awesome">
	<meta name="author" content="">

	<!-- BOOTSTRAP -->
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	
	<!-- LANCENG CSS -->
	<link href="/css/style.css" rel="stylesheet">
	<link href="/css/style-responsive.css" rel="stylesheet">
	
	<!-- VENDOR -->
	<link href="/css/animate.css" rel="stylesheet">
	<link href="/third/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/third/weather-icon/css/weather-icons.min.css" rel="stylesheet">
	<link href="/third/morris/morris.css" rel="stylesheet">
	<link href="/third/nifty-modal/css/component.css" rel="stylesheet">
	<link href="/third/sortable/sortable-theme-bootstrap.css" rel="stylesheet"> 
	<link href="/third/icheck/skins/minimal/grey.css" rel="stylesheet"> 
	<link href="/third/select/bootstrap-select.min.css" rel="stylesheet"> 
	<link href="/third/summernote/summernote.css" rel="stylesheet">
	<link href="/third/magnific-popup/magnific-popup.css" rel="stylesheet"> 
	<link href="/third/datepicker/css/datepicker.css" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	
	<!-- FAVICON -->
	<link rel="shortcut icon" href="/img/favicon.ico">
	</head>
	
	
	
	<!-- BODY -->
	<body class="tooltips full-content">
	
	
	<!-- BEGIN PAGE -->
	<div class="container">
		<?=$this->layout()->content;?>
	</div><!-- End div .container -->
	<!-- END PAGE -->

	<!--
	================================================
	JAVASCRIPT
	================================================
	-->
	<!-- Basic Javascripts (Jquery and bootstrap) -->
	<script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	
	<!-- VENDOR -->
	
	<!-- Slimscroll js -->
	<script src="/third/slimscroll/jquery.slimscroll.min.js"></script>
	
	<!-- Morris js -->
	<script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="/third/morris/morris.js"></script>
	
	<!-- Nifty modals js -->
	<script src="/third/nifty-modal/js/classie.js"></script>
	<script src="/third/nifty-modal/js/modalEffects.js"></script>
	
	<!-- Sortable js -->
	<script src="/third/sortable/sortable.min.js"></script>
	
	<!-- Bootstrao selectpicker js -->
	<script src="/third/select/bootstrap-select.min.js"></script>
	
	<!-- Summernote js -->
	<script src="/third/summernote/summernote.js"></script>
	
	<!-- Magnific popup js -->
	<script src="/third/magnific-popup/jquery.magnific-popup.min.js"></script> 
	
	<!-- Bootstrap file input js -->
	<script src="/third/input/bootstrap.file-input.js"></script>
	
	<!-- Bootstrao datepicker js -->
	<script src="/third/datepicker/js/bootstrap-datepicker.js"></script>
	
	<!-- Icheck js -->
	<script src="/third/icheck/icheck.min.js"></script>
	
	<!-- Form wizard js -->
	<script src="/third/wizard/jquery.snippet.min.js"></script>
	<script src="/third/wizard/jquery.easyWizard.js"></script>
	<script src="/third/wizard/scripts.js"></script>
	
	<!-- LANCENG TEMPLATE JAVASCRIPT -->
	<script src="/js/lanceng.js"></script>

	</body>
</html>